### PR TITLE
Add test suites

### PR DESCRIPTION
**Pull request by sunoru**
#5

### CODE REVIEW

**Comment by sunoru** [comment]
I just add a `.travis.yml` using [julia-icc-travis](https://github.com/sunoru/julia-icc-travis), and it works well now.

**Comment by simonbyrne** [comment]
I think we need to be a bit careful here about licensing: according to [the EULA](https://software.intel.com/sites/default/files/managed/32/85/Master-EULA-for-Intel-SW-Development-Products_February-2016.pdf):

> NOTWITHSTANDING ANYTHING TO THE CONTRARY ELSEWHERE IN THIS AGREEMENT, YOU MAY USE THE MATERIALS ONLY FOR EVALUATION PURPOSES AND ONLY FOR THE TERM OF THE EVALUATION, YOU MAY NOT DISTRIBUTE ANY PORTION OF THE MATERIALS, AND THE APPLICATION AND/OR PRODUCT DEVELOPED BY YOU MAY ONLY BE USED FOR EVALUATION PURPOSES AND ONLY FOR THE TERM OF THE EVALUATION.

which I'm not sure this would be adhering to. Perhaps the community license version would be better, though ideally we would get some sort of confirmation from Intel.

**Comment by sunoru** [comment]
I agree, and it's easy to use community license in the scripts. However the problem is that the license key should be stored in the account that owns the project, so perhaps the official julia group rather than me should apply for a license?

**Comment by ViralBShah** [comment]
Doesn't MKL have a license for open source usage that should not be for evaluation?

**Comment by ViralBShah** [comment]
Cc @kpamnany

**Comment by sunoru** [comment]
@ViralBShah IIRC It requires an application and then you just get an serial number.

**Comment by rprechelt** [comment]
Not sure if this has proceeded from here, but [here](https://software.intel.com//qualify-for-free-software/opensourcecontributor) is a link to register for an Open Source license for Intel's MKL. As far as I understand the EULA, this is the correct license for use on Travis/AppVeyor. Apologies if this has already been set up.

**Comment by simonbyrne** [comment]
I think the community one is the best bet. The conditions on the open source one are quite restrictive (see https://github.com/travis-ci/travis-ci/issues/4604).

**Comment by Crown421** [comment]
I think this PR is very outdated at this point.

**Pull request closed without merging**
