### PR TITLE
Call xxxI instead of xxx to support strided layout. (2nd take)

### PR DESCRIPTION
**Pull request by N5N3**
Replace #54 (my local git history get messed).

### CODE REVIEW

**Comment by Crown421** [comment]
Very nice, great improvement. Could you increment the version in the Project.toml as well? 

Unfortunately there is currently an issue with the TagBot. Will try again tomorrow to fix it and then merge.

**Review by Crown421 — APPROVED** [review]

**Comment by Crown421** [comment]
Ah, could you perhaps add a few words and maybe an example to the Readme about the new capabilities for strided arrays?

**Comment by N5N3** [comment]
Well the newly added funs's accuracy looks terrible on mac (Not supprising though.)
Should we only define them on linux/windows? I have no mac at hand so it's hard for me to test which test is broken.

**Comment by Crown421** [comment]
> Well the newly added funs's accuracy looks terrible on mac (Not supprising though.) Should we only define them on linux/windows? I have no mac at hand so it's hard for me to test which func is broken.

Are you referring to the failed tests on CI or something in addition? I have a Mac in my office, will check it out once I go back in. Since it only fails on nightly, I think there is a bit of time, might even get fixed somewhere in Base.

**Comment by N5N3** [comment]
> Are you referring to the failed tests on CI or something in addition?

Yes.

> Since it only fails on nightly, I think there is a bit of time, might even get fixed somewhere in Base.

I'm not sure if this is related to the version of `MKL_JLL` . If not, then perhaps this is bug in `Base` .

**Comment by Crown421** [comment]
Will check separately, especially since the same issue is already on main. Tag bot should be working now, so I will merge this one.

**Review by Crown421 — APPROVED** [review]
Docs added, ready to merge.

**Comment by Crown421** [comment]
Improved the test display, turns out its the `gamma` function that is failing on mac: 
https://github.com/JuliaMath/IntelVectorMath.jl/actions/runs/3832441706/jobs/6522750253#step:6:353

**Pull request merged**
